// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FotostoryStreckeDocumentDataSlicesSlice = never;

/**
 * Content for Fotostory documents
 */
interface FotostoryStreckeDocumentData {
  /**
   * Slice Zone field in *Fotostory*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: fotostory_strecke.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FotostoryStreckeDocumentDataSlicesSlice> /**
   * Meta Description field in *Fotostory*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: fotostory_strecke.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Fotostory*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fotostory_strecke.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Fotostory*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: fotostory_strecke.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Fotostory document from Prismic
 *
 * - **API ID**: `fotostory_strecke`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FotostoryStreckeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FotostoryStreckeDocumentData>,
    "fotostory_strecke",
    Lang
  >;

type InterviewDocumentDataSlicesSlice =
  | HeroSlice
  | InterviewSlice
  | QuoteSlice
  | HeadlineH2Slice;

/**
 * Content for Interview documents
 */
interface InterviewDocumentData {
  /**
   * Slice Zone field in *Interview*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: interview.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InterviewDocumentDataSlicesSlice> /**
   * Meta Description field in *Interview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: interview.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Interview*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: interview.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Interview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: interview.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Interview document from Prismic
 *
 * - **API ID**: `interview`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InterviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InterviewDocumentData>,
    "interview",
    Lang
  >;

type LongReadArticleDocumentDataSlicesSlice =
  | HeadlineLongReadH2Slice
  | TextBlockLongReadSlice;

/**
 * Content for Long Read Article documents
 */
interface LongReadArticleDocumentData {
  /**
   * Slice Zone field in *Long Read Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: long_read_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LongReadArticleDocumentDataSlicesSlice> /**
   * Meta Description field in *Long Read Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: long_read_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Long Read Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: long_read_article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Long Read Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: long_read_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Long Read Article document from Prismic
 *
 * - **API ID**: `long_read_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LongReadArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LongReadArticleDocumentData>,
    "long_read_article",
    Lang
  >;

type MeinungDocumentDataSlicesSlice = never;

/**
 * Content for Meinung documents
 */
interface MeinungDocumentData {
  /**
   * Slice Zone field in *Meinung*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: meinung.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MeinungDocumentDataSlicesSlice> /**
   * Meta Description field in *Meinung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: meinung.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Meinung*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meinung.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Meinung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: meinung.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Meinung document from Prismic
 *
 * - **API ID**: `meinung`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MeinungDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MeinungDocumentData>,
    "meinung",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TippsDocumentDataSlicesSlice = never;

/**
 * Content for Tipps documents
 */
interface TippsDocumentData {
  /**
   * Slice Zone field in *Tipps*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tipps.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TippsDocumentDataSlicesSlice> /**
   * Meta Description field in *Tipps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tipps.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Tipps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tipps.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Tipps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tipps.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Tipps document from Prismic
 *
 * - **API ID**: `tipps`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TippsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TippsDocumentData>, "tipps", Lang>;

export type AllDocumentTypes =
  | FotostoryStreckeDocument
  | InterviewDocument
  | LongReadArticleDocument
  | MeinungDocument
  | SettingsDocument
  | TippsDocument;

/**
 * Primary content in *HeadlineH2 → Primary*
 */
export interface HeadlineH2SliceDefaultPrimary {
  /**
   * headline field in *HeadlineH2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_h2.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;
}

/**
 * Default variation for HeadlineH2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineH2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineH2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadlineH2*
 */
type HeadlineH2SliceVariation = HeadlineH2SliceDefault;

/**
 * HeadlineH2 Shared Slice
 *
 * - **API ID**: `headline_h2`
 * - **Description**: HeadlineH2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineH2Slice = prismic.SharedSlice<
  "headline_h2",
  HeadlineH2SliceVariation
>;

/**
 * Primary content in *HeadlineLongReadH2 → Primary*
 */
export interface HeadlineLongReadH2SliceDefaultPrimary {
  /**
   * headline field in *HeadlineLongReadH2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_long_read_h2.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;
}

/**
 * Default variation for HeadlineLongReadH2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineLongReadH2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineLongReadH2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadlineLongReadH2*
 */
type HeadlineLongReadH2SliceVariation = HeadlineLongReadH2SliceDefault;

/**
 * HeadlineLongReadH2 Shared Slice
 *
 * - **API ID**: `headline_long_read_h2`
 * - **Description**: HeadlineLongReadH2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineLongReadH2Slice = prismic.SharedSlice<
  "headline_long_read_h2",
  HeadlineLongReadH2SliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Bild field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Interview → Items*
 */
export interface InterviewSliceDefaultItem {
  /**
   * Frage field in *Interview → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: interview.items[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Antwort field in *Interview → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: interview.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for Interview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InterviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<InterviewSliceDefaultItem>
>;

/**
 * Slice variation for *Interview*
 */
type InterviewSliceVariation = InterviewSliceDefault;

/**
 * Interview Shared Slice
 *
 * - **API ID**: `interview`
 * - **Description**: Interview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InterviewSlice = prismic.SharedSlice<
  "interview",
  InterviewSliceVariation
>;

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Default variation for TextBlockLongRead Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockLongReadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * V2 variation for TextBlockLongRead Slice
 *
 * - **API ID**: `v2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockLongReadSliceV2 = prismic.SharedSliceVariation<
  "v2",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TextBlockLongRead*
 */
type TextBlockLongReadSliceVariation =
  | TextBlockLongReadSliceDefault
  | TextBlockLongReadSliceV2;

/**
 * TextBlockLongRead Shared Slice
 *
 * - **API ID**: `text_block_long_read`
 * - **Description**: TextBlockLongRead
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockLongReadSlice = prismic.SharedSlice<
  "text_block_long_read",
  TextBlockLongReadSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FotostoryStreckeDocument,
      FotostoryStreckeDocumentData,
      FotostoryStreckeDocumentDataSlicesSlice,
      InterviewDocument,
      InterviewDocumentData,
      InterviewDocumentDataSlicesSlice,
      LongReadArticleDocument,
      LongReadArticleDocumentData,
      LongReadArticleDocumentDataSlicesSlice,
      MeinungDocument,
      MeinungDocumentData,
      MeinungDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      TippsDocument,
      TippsDocumentData,
      TippsDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeadlineH2Slice,
      HeadlineH2SliceDefaultPrimary,
      HeadlineH2SliceVariation,
      HeadlineH2SliceDefault,
      HeadlineLongReadH2Slice,
      HeadlineLongReadH2SliceDefaultPrimary,
      HeadlineLongReadH2SliceVariation,
      HeadlineLongReadH2SliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InterviewSlice,
      InterviewSliceDefaultItem,
      InterviewSliceVariation,
      InterviewSliceDefault,
      QuoteSlice,
      QuoteSliceVariation,
      QuoteSliceDefault,
      TextBlockLongReadSlice,
      TextBlockLongReadSliceVariation,
      TextBlockLongReadSliceDefault,
      TextBlockLongReadSliceV2,
    };
  }
}
