// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  headline_h2: dynamic(() => import("./HeadlineH2")),
  hero: dynamic(() => import("./Hero")),
  interview: dynamic(() => import("./Interview")),
  quote: dynamic(() => import("./Quote")),
};
